title: Dare Balogun
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  Interested in systems engineering, ASIC design, embedded development, operating systems, virtualization technologies and more. 
  I love to learn and have gotten very good at it.
  <br><br>
  Carleton University Computer Engineering soon to be new grad. 
  Looking for challenging new full time opportunities starting May 2020
  <br><br>
  <a href="https://www.linkedin.com/in/dare-balogun/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
